### ISSUE TITLE
BroadcastReciever not registered in the AndroidManifest.xml

### ISSUE THREAD

**Issue by matthewrice345** [michael-cheung-thebus/package_replaced#1]
I think that the example app and instructions are missing this:
```
        <receiver
            android:name="org.thebus.package_replaced.PackageReplacedPlugin">
            <intent-filter>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>
```

**Comment by michael-cheung-thebus** [comment]
The receiver is already in the module's manifest.  As far as I can tell from testing, it seems to work fine without needing to also be in the example's manifest.

Do you have a sample where it doesn't work unless that receiver is added to the manifest?
